apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-management
  name: user-management
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - image: us.gcr.io/ct-admin-project/capitaltyping/user-management
        imagePullPolicy: Always
        name: user-management
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always

